---
title: "Seurat init"
author: "tobiasst"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  html_document:
    df_print: paged
    code_folding: hide
---

```{r init, message=F, warning=F}
library(Seurat)
library(TxDb.Dmelanogaster.UCSC.dm6.ensGene)
```

if you run out of memory (*Error: vector memory exhausted (limit reached?)*) read here:
http://r.789695.n4.nabble.com/R-3-5-0-vector-memory-exhausted-error-on-readBin-td4750237.html
http://btibert3.github.io/2015/12/08/Environment-Variables-in-Rstudio-on-Mac.html

```{r}
bra.data <- Read10X("data/GSE107451_DGRP-551_w1118_WholeBrain_157k_0d_1d_3d_6d_9d_15d_30d_50d_10X_DGEM_MEX.mtx.tsv/")

dense.size <- object.size(x = as.matrix(x = bra.data))
dense.size

sparse.size <- object.size(x = bra.data)
sparse.size

dense.size/sparse.size

bra <- CreateSeuratObject(raw.data = bra.data, min.cells = 3, min.genes = 200, 
                          project = "Drosophila brain")

# The number of genes and UMIs (nGene and nUMI) are automatically calculated
# for every object by Seurat.  For non-UMI data, nUMI represents the sum of
# the non-normalized values within a cell We calculate the percentage of
# mitochondrial genes here and store it in percent.mito using AddMetaData.
# We use object@raw.data since this represents non-transformed and
# non-log-normalized counts The % of UMI mapping to MT-genes is a common
# scRNA-seq QC metric.
mito.genes <- grep(pattern = "^mt", x = rownames(x = bra@data), value = TRUE)
percent.mito <- Matrix::colSums(bra@raw.data[mito.genes, ])/Matrix::colSums(bra@raw.data)

# AddMetaData adds columns to object@meta.data, and is a great place to
# stash QC stats
bra <- AddMetaData(object = bra, metadata = percent.mito, col.name = "percent.mito")
VlnPlot(object = bra, features.plot = c("nGene", "nUMI", "percent.mito"), nCol = 3)

# GenePlot is typically used to visualize gene-gene relationships, but can
# be used for anything calculated by the object, i.e. columns in
# object@meta.data, PC scores etc.  Since there is a rare subset of cells
# with an outlier level of high mitochondrial percentage and also low UMI
# content, we filter these as well
par(mfrow = c(1, 2))
GenePlot(object = bra, gene1 = "nUMI", gene2 = "percent.mito")
GenePlot(object = bra, gene1 = "nUMI", gene2 = "nGene")

# We filter out cells that have unique gene counts over 2,500 or less than
# 200 Note that low.thresholds and high.thresholds are used to define a
# 'gate'.  -Inf and Inf should be used if you don't want a lower or upper
# threshold.
bra <- FilterCells(object = bra, subset.names = c("nGene", "nUMI","percent.mito"), 
    low.thresholds = c(200,-Inf, -Inf), high.thresholds = c(4000, 40000, 0.05))

bra <- NormalizeData(object = bra, normalization.method = "LogNormalize", 
    scale.factor = 10000)

bra <- FindVariableGenes(object = bra, mean.function = ExpMean, dispersion.function = LogVMR, 
    x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.5)
length(x = bra@var.genes)

bra <- ScaleData(object = bra, vars.to.regress = c("nUMI", "percent.mito"))

bra <- RunPCA(object = bra, pc.genes = bra@var.genes, do.print = TRUE, pcs.print = 1:5, 
    genes.print = 5)

VizPCA(object = bra, pcs.use = 1:2)

PCAPlot(object = bra, dim.1 = 1, dim.2 = 2)

# takes too long
#bra <- JackStraw(object = bra, num.replicate = 100, display.progress = FALSE)
#JackStrawPlot(object = bra, PCs = 1:12)

PCElbowPlot(object = bra)

bra <- FindClusters(object = bra, reduction.type = "pca", dims.use = 1:15, 
    resolution = 0.6, print.output = 0, save.SNN = TRUE)
PrintFindClustersParams(object = bra)
bra <- RunTSNE(object = bra, dims.use = 1:10, do.fast = TRUE)

TSNEPlot(object = bra)

saveRDS(bra, "bra_157k.rds")
```

```{r}
sessionInfo()
```

